services:
  sms-gateway:
    build: .
    container_name: sms_gateway
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/mydb
      DB_USER: Ieqbli
      DB_PASS: Mamali@2005
      SMS_DRIVER: twilio
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: Ieqbli
      POSTGRES_PASSWORD: Mamali@2005
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: